Disable RocksDB memory mapped files on Windows
Allowing MMapped files on Windows for rocksdb produces the
following error when inserting a large (>1M) objects through putAll():

org.rocksdb.RocksDBException: IO error: Failed to FlushViewOfFile: .../000015.sst:
The process cannot access the file because another process has locked a portion of the file.
at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-4.11.2.jar:na]
at org.rocksdb.RocksDB.write(RocksDB.java:555) ~[rocksdbjni-4.11.2.jar:na]
at org.locationtech.geogig.rocksdb.RocksdbObjectStore.putAll(RocksdbObjectStore.java:371)

(Note: DBoptions.setAllowOsBuffer(true) is removed since it defaults to true
anyways and it's removed in rocksdb 5.x)

Signed-off-by: Gabriel Roldan <groldan@boundlessgeo.com>